apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: odoo-estate
  namespace: argocd
spec:
  goTemplate: true
  generators:
    - pullRequest:
      github:
        owner: nikolinmajmari
        repo: odoo_estate_tutorial
      requeueAfterSeconds: 60
  template:
    metadata:
      name: 'odoo-estate-{{.branch}}'
  project: default
  source:
    repoURL: 'https://github.com/nikolinmajmari/odoo_estate_tutorial.git'
    targetRevision: main
    path: helm
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true