version: '2'
services: 
  web:
    image: odoo:17.0
    command: --dev=all
    depends_on:
      - db
    ports:
      - 8069:8069
    volumes:
      - type: bind
        source: ./custom-modules
        target: /mnt/extra-addons
  db:
    image: postgres:13
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo