services: 
  web:
    image: odoo:17.0
    command: ${ODOO_CMD_ARGS} --addons-path=/mnt/extra-addons/base
    depends_on:
      - db
    ports:
      - ${ODOO_EXPOSE_PORT}:8069
    volumes:
      - ${SOFTCELL_BASE_ADDONS_PATH}:/mnt/extra-addons/base
  db:
    image: postgres:13
    ports:
      - ${POSTGRES_EXPOSE_PORT}:5432
    volumes:
      - ./postgress_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
volumes:
  postgress_data: