version: '3'
services: 
  web:
    image: odoo:17.0
    container_name: odoo_estate_test
    command: -d test --db_host db --db_password odoo --log-level=test --test-enable --stop-after-init --no-http -i web --addons-path=/mnt/extra-addons/
    depends_on:
      - db
    ports:
      - 80:8069
    volumes:
      - ./config:/etc/odoo
      - ./custom-modules:/mnt/extra-addons
  db:
    image: postgres:13
    container_name: odoo_estate_postgresql_test
    ports:
      - 5432:5432
    volumes:
      - ./postgress_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo

volumes:
  postgress_data:

