version: '3'
services: 
  web:
    image: odoo:17.0
    container_name: odoo_estate
    command: ${ODOO_CMD_ARGS} --addons-path=/mnt/extra-addons/
    depends_on:
      - db
    ports:
      - 8069:8069
    volumes:
      - ./config:/etc/odoo
      - ./custom-modules:/mnt/extra-addons
  db:
    image: postgres:13
    container_name: odoo_estate_postgresql
    ports:
      - 5432:5432
    volumes:
      - ./postgress_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo

volumes:
  postgress_data:

