apiVersion: apps/v1
kind: Deployment
metadata:
  name: odoo
  namespace: saas-1
spec:
  selector:
    matchLabels:
      app: odoo
  template:
    metadata:
      labels:
        app: odoo
    spec:
      containers:
        - name: odoo
          image: nikolinmajmari/odoo_estate
          env:
            - name: ODOO_CMD_ARGS
              value: ""
            - name: POSTGRES_DB
              value: "postgres"
            - name: POSTGRES_USER
              value: "odoo"
            - name: POSTGRES_PASSWORD
              value: "odoo"
            - name: HOST
              value: "postgres"
          ports:
            - containerPort: 8069
---
apiVersion: v1
kind: Service
metadata:
  name: odoo
  namespace: saas-1
spec:
  selector:
    app: odoo
  ports:
    - protocol: TCP
      port: 8069
      targetPort: 8069